In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df = pd.read_csv('house.csv')
df.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [14]:
df.shape

(1460, 81)

In [15]:
df.size

118260

In [16]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [17]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [18]:
df = df[['GrLivArea', 'YearBuilt', 'GarageCars', 'TotalBsmtSF',
    'FullBath', 'OverallQual', 'Neighborhood', 'SalePrice']]

In [19]:
df

,GrLivArea,YearBuilt,GarageCars,TotalBsmtSF,FullBath,OverallQual,Neighborhood,SalePrice
0,1710,2003,2,856,2,7,CollgCr,208500
1,1262,1976,2,1262,2,6,Veenker,181500
2,1786,2001,2,920,2,7,CollgCr,223500
3,1717,1915,3,756,1,7,Crawfor,140000
4,2198,2000,3,1145,2,8,NoRidge,250000
...,...,...,...,...,...,...,...,...
1455,1647,1999,2,953,2,6,Gilbert,175000
1456,2073,1978,2,1542,2,6,NWAmes,210000
1457,2340,1941,1,1152,2,7,Crawfor,266500
1458,1078,1950,1,1078,1,5,NAmes,142125
1459,1256,1965,1,1256,1,5,Edwards,147500

In [20]:
df.to_csv('data_clean.csv', index=False)

In [22]:
df['Neighborhood'].unique()

array(['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',
       'NWAmes', 'OldTown', 'BrkSide', 'Sawyer', 'NridgHt', 'NAmes',
       'SawyerW', 'IDOTRR', 'MeadowV', 'Edwards', 'Timber', 'Gilbert',
       'StoneBr', 'ClearCr', 'NPkVill', 'Blmngtn', 'BrDale', 'SWISU',
       'Blueste'], dtype=object)

In [23]:
df['Neighborhood'].nunique()

25

In [28]:
df.groupby('Neighborhood')['SalePrice'].mean().round().sort_values(ascending=False).head(5)

Neighborhood
NoRidge    335295.0
NridgHt    316271.0
StoneBr    310499.0
Timber     242247.0
Veenker    238773.0
Name: SalePrice, dtype: float64

In [34]:
n = (df['YearBuilt'] > 2000).sum()
print(f'Количество домов было построено после 2000 года: {n}')

Количество домов было построено после 2000 года: 364

In [36]:
df[df['YearBuilt'] > 2000]

,GrLivArea,YearBuilt,GarageCars,TotalBsmtSF,FullBath,OverallQual,Neighborhood,SalePrice
0,1710,2003,2,856,2,7,CollgCr,208500
2,1786,2001,2,920,2,7,CollgCr,223500
6,1694,2004,2,1686,2,8,Somerst,307000
11,2324,2005,3,1175,3,9,NridgHt,345000
13,1494,2006,3,1494,2,7,CollgCr,279500
...,...,...,...,...,...,...,...,...
1444,1422,2004,2,1422,2,7,CollgCr,179600
1451,1578,2008,3,1573,2,8,Somerst,287090
1452,1072,2005,2,547,1,5,Edwards,145000
1453,1140,2006,0,1140,1,5,Mitchel,84500
1454,1221,2004,2,1221,2,7,Somerst,185000

In [38]:
df.groupby('OverallQual')['GrLivArea'].mean().round()

OverallQual
1      619.0
2      573.0
3     1119.0
4     1107.0
5     1251.0
6     1466.0
7     1704.0
8     1948.0
9     2078.0
10    3001.0
Name: GrLivArea, dtype: float64

In [55]:
count_zero = (df['TotalBsmtSF'] == 0).sum()
count_zero

np.int64(37)

In [60]:
k = round((count_zero * 100) / 1460, 2)
print(f'Доля: {k}%')

Доля: 2.53%

In [42]:
df[df['TotalBsmtSF'] == 0]

,GrLivArea,YearBuilt,GarageCars,TotalBsmtSF,FullBath,OverallQual,Neighborhood,SalePrice
17,1296,1967,2,0,2,4,Sawyer,90000
39,1152,1955,0,0,2,4,Edwards,82000
90,1040,1950,2,0,1,4,NAmes,109900
102,1535,1979,2,0,2,5,SawyerW,118964
156,1040,1950,2,0,1,5,NAmes,109500
182,1340,1957,1,0,1,5,Edwards,120000
259,882,1956,1,0,1,5,OldTown,97000
342,1040,1949,2,0,2,3,NAmes,87500
362,1922,2003,2,0,3,7,Edwards,198500
371,1588,1959,2,0,2,4,ClearCr,134432
392,882,1959,1,0,1,5,NAmes,106500
520,1294,1900,0,0,2,4,OldTown,106250
532,827,1955,1,0,1,5,NAmes,107500
533,334,1946,0,0,1,1,BrkSide,39300
553,1126,1949,2,0,2,4,Edwards,108000
646,1048,1950,2,0,1,5,NAmes,98300
705,1092,1930,0,0,2,4,IDOTRR,55000
736,1040,1950,2,0,2,3,NAmes,93500
749,1529,1945,1,0,2,4,Edwards,98000
778,2020,1977,2,0,2,5,SawyerW,144000
868,2320,1948,2,0,2,5,Gilbert,169000
894,1535,1979,2,0,2,5,SawyerW,118858
897,2240,1979,2,0,2,5,SawyerW,142953
984,1734,1977,2,0,2,5,Mitchel,126000
1000,944,1952,2,0,1,3,Edwards,82000
1011,1664,1965,0,0,2,5,Edwards,100000
1035,845,1957,1,0,1,4,Edwards,84000
1045,1733,1955,2,0,2,3,Edwards,139600
1048,1771,1960,2,0,1,5,Mitchel,115000
1049,930,1946,1,0,1,4,Edwards,84900
1090,1040,1950,2,0,2,3,NAmes,92900
1179,1124,1954,0,0,1,5,Edwards,93000
1216,1902,1978,2,0,2,6,Sawyer,112000
1218,912,1947,0,0,1,4,BrkSide,80500
1232,1224,1962,2,0,2,4,NAmes,101800
1321,720,1949,1,0,1,3,BrkSide,72500
1412,1040,1949,2,0,2,4,NAmes,90000

In [44]:
df.groupby('GarageCars')['SalePrice'].mean().round()

GarageCars
0    103317.0
1    128117.0
2    183852.0
3    309636.0
4    192656.0
Name: SalePrice, dtype: float64

In [47]:
(df['FullBath'] > 2).sum()

np.int64(33)

In [49]:
df[df['FullBath'] > 2]

,GrLivArea,YearBuilt,GarageCars,TotalBsmtSF,FullBath,OverallQual,Neighborhood,SalePrice
11,2324,2005,3,1175,3,9,NridgHt,345000
20,2376,2005,3,1158,3,8,NridgHt,325300
35,2452,2004,3,1117,3,8,NridgHt,309000
58,2945,2006,3,1410,3,10,StoneBr,438780
118,3222,1990,3,1673,3,7,SawyerW,320000
137,1959,1988,3,1907,3,7,Mitchel,171000
304,3493,1880,3,1470,3,7,OldTown,295000
320,2596,2006,3,1249,3,9,NridgHt,342643
362,1922,2003,2,0,3,7,Edwards,198500
377,2466,2004,2,1580,3,8,Somerst,340000
496,3228,1992,2,3200,3,8,NoRidge,430000
523,4676,2007,3,3138,3,10,Edwards,184750
529,2515,1957,2,2035,3,6,Crawfor,200624
583,2775,1893,2,1237,3,10,OldTown,325000
607,2008,1948,1,896,3,5,Edwards,225000
686,1761,2007,2,874,3,7,Somerst,227875
691,4316,1994,3,2444,3,10,NoRidge,755000
738,1200,1987,0,1200,3,5,Edwards,179000
745,2715,1976,2,1142,3,8,NWAmes,299800
769,3279,2003,3,1650,3,8,StoneBr,538000
798,3140,2008,3,1926,3,9,NridgHt,485000
803,2822,2008,3,1734,3,9,NridgHt,582933
848,2358,1908,2,907,3,6,ClearCr,240000
1046,2868,2005,3,1992,3,9,StoneBr,556581
1142,2828,2006,3,1466,3,8,CollgCr,424870
1169,3627,1995,3,1930,3,10,NoRidge,625000
1173,3086,1946,0,1598,3,5,ClearCr,200500
1182,4476,1996,3,2396,3,10,NoRidge,745000
1245,1868,1984,2,585,3,6,NWAmes,178000
1268,3447,1935,3,728,3,8,Crawfor,381000
1355,1920,1968,2,570,3,7,NWAmes,170000
1360,2601,1921,2,612,3,5,SWISU,189000
1386,2784,1978,2,1392,3,7,NWAmes,250000

In [63]:
df['Neighborhood'].value_counts().head(1)

Neighborhood
NAmes    225
Name: count, dtype: int64

In [65]:
df.corr(numeric_only=True)

,GrLivArea,YearBuilt,GarageCars,TotalBsmtSF,FullBath,OverallQual,SalePrice
GrLivArea,1.000000,0.199010,0.467247,0.454868,0.630012,0.593007,0.708624
YearBuilt,0.199010,1.000000,0.537850,0.391452,0.468271,0.572323,0.522897
GarageCars,0.467247,0.537850,1.000000,0.434585,0.469672,0.600671,0.640409
TotalBsmtSF,0.454868,0.391452,0.434585,1.000000,0.323722,0.537808,0.613581
FullBath,0.630012,0.468271,0.469672,0.323722,1.000000,0.550600,0.560664
OverallQual,0.593007,0.572323,0.600671,0.537808,0.550600,1.000000,0.790982
SalePrice,0.708624,0.522897,0.640409,0.613581,0.560664,0.790982,1.000000

In [70]:
from numpy._core.defchararray import index
new_df = df.groupby('Neighborhood')['SalePrice'].mean().round().sort_values()
new_df.to_csv('ratings.csv')